export interface City {
  name: string;
  slug: string;
  state: string;
  tier: 'metro' | 'tier2' | 'tier3';
  population: string;
}

export const CITIES: City[] = [
  { name: 'Mumbai', slug: 'mumbai', state: 'Maharashtra', tier: 'metro', population: '20M+' },
  { name: 'Delhi', slug: 'delhi', state: 'Delhi', tier: 'metro', population: '30M+' },
  { name: 'Bangalore', slug: 'bangalore', state: 'Karnataka', tier: 'metro', population: '12M+' },
  { name: 'Hyderabad', slug: 'hyderabad', state: 'Telangana', tier: 'metro', population: '10M+' },
  { name: 'Chennai', slug: 'chennai', state: 'Tamil Nadu', tier: 'metro', population: '11M+' },
  { name: 'Kolkata', slug: 'kolkata', state: 'West Bengal', tier: 'metro', population: '15M+' },
  { name: 'Pune', slug: 'pune', state: 'Maharashtra', tier: 'metro', population: '7M+' },
  { name: 'Ahmedabad', slug: 'ahmedabad', state: 'Gujarat', tier: 'metro', population: '8M+' },
  { name: 'Jaipur', slug: 'jaipur', state: 'Rajasthan', tier: 'tier2', population: '4M+' },
  { name: 'Surat', slug: 'surat', state: 'Gujarat', tier: 'tier2', population: '6M+' },
  { name: 'Lucknow', slug: 'lucknow', state: 'Uttar Pradesh', tier: 'tier2', population: '4M+' },
  { name: 'Kanpur', slug: 'kanpur', state: 'Uttar Pradesh', tier: 'tier2', population: '3M+' },
  { name: 'Nagpur', slug: 'nagpur', state: 'Maharashtra', tier: 'tier2', population: '2.5M+' },
  { name: 'Visakhapatnam', slug: 'visakhapatnam', state: 'Andhra Pradesh', tier: 'tier2', population: '2M+' },
  { name: 'Indore', slug: 'indore', state: 'Madhya Pradesh', tier: 'tier2', population: '2.5M+' },
  { name: 'Thane', slug: 'thane', state: 'Maharashtra', tier: 'tier2', population: '2M+' },
  { name: 'Bhopal', slug: 'bhopal', state: 'Madhya Pradesh', tier: 'tier2', population: '2M+' },
  { name: 'Patna', slug: 'patna', state: 'Bihar', tier: 'tier2', population: '2.5M+' },
  { name: 'Vadodara', slug: 'vadodara', state: 'Gujarat', tier: 'tier2', population: '2M+' },
  { name: 'Ghaziabad', slug: 'ghaziabad', state: 'Uttar Pradesh', tier: 'tier2', population: '1.5M+' },
  { name: 'Ludhiana', slug: 'ludhiana', state: 'Punjab', tier: 'tier2', population: '1.6M+' },
  { name: 'Agra', slug: 'agra', state: 'Uttar Pradesh', tier: 'tier2', population: '1.8M+' },
  { name: 'Nashik', slug: 'nashik', state: 'Maharashtra', tier: 'tier2', population: '1.5M+' },
  { name: 'Faridabad', slug: 'faridabad', state: 'Haryana', tier: 'tier2', population: '1.4M+' },
  { name: 'Meerut', slug: 'meerut', state: 'Uttar Pradesh', tier: 'tier2', population: '1.3M+' },
  { name: 'Rajkot', slug: 'rajkot', state: 'Gujarat', tier: 'tier2', population: '1.3M+' },
  { name: 'Varanasi', slug: 'varanasi', state: 'Uttar Pradesh', tier: 'tier2', population: '1.2M+' },
  { name: 'Srinagar', slug: 'srinagar', state: 'Jammu and Kashmir', tier: 'tier2', population: '1.2M+' },
  { name: 'Aurangabad', slug: 'aurangabad', state: 'Maharashtra', tier: 'tier2', population: '1.1M+' },
  { name: 'Amritsar', slug: 'amritsar', state: 'Punjab', tier: 'tier2', population: '1.1M+' },
  { name: 'Allahabad', slug: 'allahabad', state: 'Uttar Pradesh', tier: 'tier2', population: '1.2M+' },
  { name: 'Ranchi', slug: 'ranchi', state: 'Jharkhand', tier: 'tier2', population: '1.1M+' },
  { name: 'Howrah', slug: 'howrah', state: 'West Bengal', tier: 'tier2', population: '1M+' },
  { name: 'Coimbatore', slug: 'coimbatore', state: 'Tamil Nadu', tier: 'tier2', population: '2.1M+' },
  { name: 'Jabalpur', slug: 'jabalpur', state: 'Madhya Pradesh', tier: 'tier2', population: '1.4M+' },
  { name: 'Gwalior', slug: 'gwalior', state: 'Madhya Pradesh', tier: 'tier2', population: '1.1M+' },
  { name: 'Vijayawada', slug: 'vijayawada', state: 'Andhra Pradesh', tier: 'tier2', population: '1.5M+' },
  { name: 'Jodhpur', slug: 'jodhpur', state: 'Rajasthan', tier: 'tier2', population: '1.1M+' },
  { name: 'Madurai', slug: 'madurai', state: 'Tamil Nadu', tier: 'tier2', population: '1.5M+' },
  { name: 'Raipur', slug: 'raipur', state: 'Chhattisgarh', tier: 'tier2', population: '1.1M+' },
  { name: 'Kota', slug: 'kota', state: 'Rajasthan', tier: 'tier2', population: '1.1M+' },
  { name: 'Guwahati', slug: 'guwahati', state: 'Assam', tier: 'tier2', population: '1M+' },
  { name: 'Chandigarh', slug: 'chandigarh', state: 'Chandigarh', tier: 'tier2', population: '1.2M+' },
  { name: 'Solapur', slug: 'solapur', state: 'Maharashtra', tier: 'tier2', population: '1.1M+' },
  { name: 'Hubballi', slug: 'hubballi', state: 'Karnataka', tier: 'tier2', population: '1M+' },
  { name: 'Bareilly', slug: 'bareilly', state: 'Uttar Pradesh', tier: 'tier2', population: '1M+' },
  { name: 'Mysuru', slug: 'mysuru', state: 'Karnataka', tier: 'tier2', population: '1.2M+' },
  { name: 'Moradabad', slug: 'moradabad', state: 'Uttar Pradesh', tier: 'tier2', population: '900K+' },
  { name: 'Gurgaon', slug: 'gurgaon', state: 'Haryana', tier: 'tier2', population: '900K+' },
  { name: 'Aligarh', slug: 'aligarh', state: 'Uttar Pradesh', tier: 'tier2', population: '870K+' },
  { name: 'Jalandhar', slug: 'jalandhar', state: 'Punjab', tier: 'tier2', population: '870K+' },
  { name: 'Tiruchirappalli', slug: 'tiruchirappalli', state: 'Tamil Nadu', tier: 'tier2', population: '1M+' },
  { name: 'Bhubaneswar', slug: 'bhubaneswar', state: 'Odisha', tier: 'tier2', population: '900K+' },
  { name: 'Salem', slug: 'salem', state: 'Tamil Nadu', tier: 'tier2', population: '830K+' },
  { name: 'Thiruvananthapuram', slug: 'thiruvananthapuram', state: 'Kerala', tier: 'tier2', population: '1.7M+' },
  { name: 'Guntur', slug: 'guntur', state: 'Andhra Pradesh', tier: 'tier2', population: '740K+' },
  { name: 'Amravati', slug: 'amravati', state: 'Maharashtra', tier: 'tier2', population: '650K+' },
  { name: 'Bikaner', slug: 'bikaner', state: 'Rajasthan', tier: 'tier2', population: '700K+' },
  { name: 'Noida', slug: 'noida', state: 'Uttar Pradesh', tier: 'tier2', population: '640K+' },
  { name: 'Jamshedpur', slug: 'jamshedpur', state: 'Jharkhand', tier: 'tier2', population: '1.3M+' },
  { name: 'Bhilai', slug: 'bhilai', state: 'Chhattisgarh', tier: 'tier2', population: '600K+' },
  { name: 'Cuttack', slug: 'cuttack', state: 'Odisha', tier: 'tier2', population: '610K+' },
  { name: 'Kochi', slug: 'kochi', state: 'Kerala', tier: 'tier2', population: '2.1M+' },
  { name: 'Dehradun', slug: 'dehradun', state: 'Uttarakhand', tier: 'tier2', population: '800K+' },
  { name: 'Durgapur', slug: 'durgapur', state: 'West Bengal', tier: 'tier2', population: '600K+' },
  { name: 'Asansol', slug: 'asansol', state: 'West Bengal', tier: 'tier2', population: '1.2M+' },
  { name: 'Nanded', slug: 'nanded', state: 'Maharashtra', tier: 'tier2', population: '550K+' },
  { name: 'Kolhapur', slug: 'kolhapur', state: 'Maharashtra', tier: 'tier2', population: '600K+' },
  { name: 'Ajmer', slug: 'ajmer', state: 'Rajasthan', tier: 'tier2', population: '540K+' },
  { name: 'Jamnagar', slug: 'jamnagar', state: 'Gujarat', tier: 'tier2', population: '600K+' },
  { name: 'Ujjain', slug: 'ujjain', state: 'Madhya Pradesh', tier: 'tier2', population: '515K+' },
  { name: 'Siliguri', slug: 'siliguri', state: 'West Bengal', tier: 'tier2', population: '700K+' },
  { name: 'Jhansi', slug: 'jhansi', state: 'Uttar Pradesh', tier: 'tier2', population: '505K+' },
  { name: 'Nellore', slug: 'nellore', state: 'Andhra Pradesh', tier: 'tier2', population: '530K+' },
  { name: 'Jammu', slug: 'jammu', state: 'Jammu and Kashmir', tier: 'tier2', population: '503K+' },
  { name: 'Mangaluru', slug: 'mangaluru', state: 'Karnataka', tier: 'tier2', population: '623K+' },
  { name: 'Udaipur', slug: 'udaipur', state: 'Rajasthan', tier: 'tier2', population: '474K+' },
  { name: 'Kozhikode', slug: 'kozhikode', state: 'Kerala', tier: 'tier2', population: '609K+' },
  { name: 'Kurnool', slug: 'kurnool', state: 'Andhra Pradesh', tier: 'tier2', population: '484K+' },
  { name: 'Bellary', slug: 'bellary', state: 'Karnataka', tier: 'tier2', population: '410K+' },
  { name: 'Patiala', slug: 'patiala', state: 'Punjab', tier: 'tier2', population: '406K+' },
  { name: 'Bhagalpur', slug: 'bhagalpur', state: 'Bihar', tier: 'tier2', population: '410K+' },
  { name: 'Muzaffarnagar', slug: 'muzaffarnagar', state: 'Uttar Pradesh', tier: 'tier2', population: '393K+' },
  { name: 'Latur', slug: 'latur', state: 'Maharashtra', tier: 'tier2', population: '382K+' },
  { name: 'Dhule', slug: 'dhule', state: 'Maharashtra', tier: 'tier2', population: '341K+' },
  { name: 'Rohtak', slug: 'rohtak', state: 'Haryana', tier: 'tier2', population: '374K+' },
  { name: 'Bhilwara', slug: 'bhilwara', state: 'Rajasthan', tier: 'tier2', population: '340K+' },
  { name: 'Muzaffarpur', slug: 'muzaffarpur', state: 'Bihar', tier: 'tier2', population: '394K+' },
  { name: 'Ahmednagar', slug: 'ahmednagar', state: 'Maharashtra', tier: 'tier2', population: '350K+' },
  { name: 'Mathura', slug: 'mathura', state: 'Uttar Pradesh', tier: 'tier2', population: '441K+' },
  { name: 'Kollam', slug: 'kollam', state: 'Kerala', tier: 'tier2', population: '349K+' },
  { name: 'Kadapa', slug: 'kadapa', state: 'Andhra Pradesh', tier: 'tier2', population: '342K+' },
  { name: 'Sambalpur', slug: 'sambalpur', state: 'Odisha', tier: 'tier2', population: '335K+' },
  { name: 'Bilaspur', slug: 'bilaspur', state: 'Chhattisgarh', tier: 'tier2', population: '495K+' },
  { name: 'Shahjahanpur', slug: 'shahjahanpur', state: 'Uttar Pradesh', tier: 'tier2', population: '333K+' },
  { name: 'Satara', slug: 'satara', state: 'Maharashtra', tier: 'tier2', population: '310K+' },
  { name: 'Bijapur', slug: 'bijapur', state: 'Karnataka', tier: 'tier2', population: '327K+' },
  { name: 'Rampur', slug: 'rampur', state: 'Uttar Pradesh', tier: 'tier2', population: '325K+' },
  { name: 'Navi Mumbai', slug: 'navi-mumbai', state: 'Maharashtra', tier: 'tier2', population: '1.1M+' },
  { name: 'Bhiwandi', slug: 'bhiwandi', state: 'Maharashtra', tier: 'tier2', population: '710K+' },
  { name: 'Saharanpur', slug: 'saharanpur', state: 'Uttar Pradesh', tier: 'tier2', population: '703K+' },
  { name: 'Firozabad', slug: 'firozabad', state: 'Uttar Pradesh', tier: 'tier2', population: '604K+' },
  { name: 'Bhavnagar', slug: 'bhavnagar', state: 'Gujarat', tier: 'tier2', population: '605K+' },
  { name: 'Kalyan', slug: 'kalyan', state: 'Maharashtra', tier: 'tier2', population: '1.25M+' },
  { name: 'Vasai Virar', slug: 'vasai-virar', state: 'Maharashtra', tier: 'tier2', population: '1.22M+' },
  { name: 'Loni', slug: 'loni', state: 'Uttar Pradesh', tier: 'tier2', population: '516K+' },
  { name: 'Ulhasnagar', slug: 'ulhasnagar', state: 'Maharashtra', tier: 'tier2', population: '506K+' },
  { name: 'Bokaro', slug: 'bokaro', state: 'Jharkhand', tier: 'tier2', population: '563K+' },
  { name: 'Dhanbad', slug: 'dhanbad', state: 'Jharkhand', tier: 'tier2', population: '1.16M+' },
  { name: 'Maheshtala', slug: 'maheshtala', state: 'West Bengal', tier: 'tier2', population: '449K+' },
  { name: 'Agartala', slug: 'agartala', state: 'Tripura', tier: 'tier3', population: '400K+' },
  { name: 'Bhatpara', slug: 'bhatpara', state: 'West Bengal', tier: 'tier3', population: '446K+' },
  { name: 'Panihati', slug: 'panihati', state: 'West Bengal', tier: 'tier3', population: '375K+' },
  { name: 'Korba', slug: 'korba', state: 'Chhattisgarh', tier: 'tier3', population: '358K+' },
  { name: 'Belagavi', slug: 'belagavi', state: 'Karnataka', tier: 'tier2', population: '610K+' },
  { name: 'Ichalkaranji', slug: 'ichalkaranji', state: 'Maharashtra', tier: 'tier3', population: '308K+' },
  { name: 'Malegaon', slug: 'malegaon', state: 'Maharashtra', tier: 'tier2', population: '471K+' },
  { name: 'Gaya', slug: 'gaya', state: 'Bihar', tier: 'tier2', population: '474K+' },
  { name: 'Jalgaon', slug: 'jalgaon', state: 'Maharashtra', tier: 'tier2', population: '460K+' },
  { name: 'Begusarai', slug: 'begusarai', state: 'Bihar', tier: 'tier3', population: '252K+' },
  { name: 'Brahmapur', slug: 'brahmapur', state: 'Odisha', tier: 'tier2', population: '367K+' },
  { name: 'Shimla', slug: 'shimla', state: 'Himachal Pradesh', tier: 'tier3', population: '169K+' },
  { name: 'Durg', slug: 'durg', state: 'Chhattisgarh', tier: 'tier3', population: '268K+' },
  { name: 'Raurkela', slug: 'raurkela', state: 'Odisha', tier: 'tier3', population: '290K+' },
  { name: 'Panipat', slug: 'panipat', state: 'Haryana', tier: 'tier3', population: '294K+' },
  { name: 'Karimnagar', slug: 'karimnagar', state: 'Telangana', tier: 'tier3', population: '297K+' },
  { name: 'Parbhani', slug: 'parbhani', state: 'Maharashtra', tier: 'tier3', population: '307K+' },
  { name: 'Etawah', slug: 'etawah', state: 'Uttar Pradesh', tier: 'tier3', population: '256K+' },
  { name: 'Bharatpur', slug: 'bharatpur', state: 'Rajasthan', tier: 'tier3', population: '252K+' },
  { name: 'Sonipat', slug: 'sonipat', state: 'Haryana', tier: 'tier3', population: '270K+' },
  { name: 'Nagercoil', slug: 'nagercoil', state: 'Tamil Nadu', tier: 'tier3', population: '224K+' },
  { name: 'Tumkur', slug: 'tumkur', state: 'Karnataka', tier: 'tier3', population: '305K+' },
  { name: 'Kharagpur', slug: 'kharagpur', state: 'West Bengal', tier: 'tier3', population: '293K+' },
  { name: 'Akola', slug: 'akola', state: 'Maharashtra', tier: 'tier3', population: '425K+' },
  { name: 'Nizamabad', slug: 'nizamabad', state: 'Telangana', tier: 'tier3', population: '311K+' },
  { name: 'Tirupati', slug: 'tirupati', state: 'Andhra Pradesh', tier: 'tier3', population: '287K+' },
  { name: 'Karnal', slug: 'karnal', state: 'Haryana', tier: 'tier3', population: '284K+' },
  { name: 'Bathinda', slug: 'bathinda', state: 'Punjab', tier: 'tier3', population: '285K+' },
  { name: 'Shivamogga', slug: 'shivamogga', state: 'Karnataka', tier: 'tier3', population: '322K+' },
  { name: 'Ratlam', slug: 'ratlam', state: 'Madhya Pradesh', tier: 'tier3', population: '265K+' },
  { name: 'Darbhanga', slug: 'darbhanga', state: 'Bihar', tier: 'tier3', population: '296K+' },
  { name: 'Erode', slug: 'erode', state: 'Tamil Nadu', tier: 'tier3', population: '214K+' },
  { name: 'Purnia', slug: 'purnia', state: 'Bihar', tier: 'tier3', population: '264K+' },
  { name: 'Sagar', slug: 'sagar', state: 'Madhya Pradesh', tier: 'tier3', population: '274K+' },
  { name: 'Imphal', slug: 'imphal', state: 'Manipur', tier: 'tier3', population: '264K+' },
  { name: 'Hapur', slug: 'hapur', state: 'Uttar Pradesh', tier: 'tier3', population: '211K+' },
  { name: 'Jind', slug: 'jind', state: 'Haryana', tier: 'tier3', population: '196K+' },
  { name: 'Thanjavur', slug: 'thanjavur', state: 'Tamil Nadu', tier: 'tier3', population: '222K+' },
  { name: 'Warangal', slug: 'warangal', state: 'Telangana', tier: 'tier3', population: '811K+' },
  { name: 'Rajnandgaon', slug: 'rajnandgaon', state: 'Chhattisgarh', tier: 'tier3', population: '163K+' },
  { name: 'Pondicherry', slug: 'pondicherry', state: 'Puducherry', tier: 'tier3', population: '244K+' },
  { name: 'Bidar', slug: 'bidar', state: 'Karnataka', tier: 'tier3', population: '202K+' },
  { name: 'Nandyal', slug: 'nandyal', state: 'Andhra Pradesh', tier: 'tier3', population: '220K+' },
  { name: 'Eluru', slug: 'eluru', state: 'Andhra Pradesh', tier: 'tier3', population: '215K+' },
  { name: 'Ongole', slug: 'ongole', state: 'Andhra Pradesh', tier: 'tier3', population: '200K+' },
  { name: 'Anantapur', slug: 'anantapur', state: 'Andhra Pradesh', tier: 'tier3', population: '245K+' },
  { name: 'Hospet', slug: 'hospet', state: 'Karnataka', tier: 'tier3', population: '206K+' },
  { name: 'Tenali', slug: 'tenali', state: 'Andhra Pradesh', tier: 'tier3', population: '170K+' },
  { name: 'Rajahmundry', slug: 'rajahmundry', state: 'Andhra Pradesh', tier: 'tier3', population: '341K+' },
  { name: 'Kakinada', slug: 'kakinada', state: 'Andhra Pradesh', tier: 'tier3', population: '312K+' },
  { name: 'Vellore', slug: 'vellore', state: 'Tamil Nadu', tier: 'tier3', population: '423K+' },
  { name: 'Cuddalore', slug: 'cuddalore', state: 'Tamil Nadu', tier: 'tier3', population: '173K+' },
  { name: 'Kumbakonam', slug: 'kumbakonam', state: 'Tamil Nadu', tier: 'tier3', population: '140K+' },
  { name: 'Dindigul', slug: 'dindigul', state: 'Tamil Nadu', tier: 'tier3', population: '214K+' },
  { name: 'Tirupur', slug: 'tirupur', state: 'Tamil Nadu', tier: 'tier3', population: '444K+' },
  { name: 'Karur', slug: 'karur', state: 'Tamil Nadu', tier: 'tier3', population: '102K+' },
  { name: 'Udupi', slug: 'udupi', state: 'Karnataka', tier: 'tier3', population: '165K+' },
  { name: 'Hassan', slug: 'hassan', state: 'Karnataka', tier: 'tier3', population: '133K+' },
  { name: 'Davanagere', slug: 'davanagere', state: 'Karnataka', tier: 'tier3', population: '435K+' },
  { name: 'Haveri', slug: 'haveri', state: 'Karnataka', tier: 'tier3', population: '68K+' },
  { name: 'Chitradurga', slug: 'chitradurga', state: 'Karnataka', tier: 'tier3', population: '115K+' },
  { name: 'Gadag', slug: 'gadag', state: 'Karnataka', tier: 'tier3', population: '93K+' },
  { name: 'Raichur', slug: 'raichur', state: 'Karnataka', tier: 'tier3', population: '232K+' },
  { name: 'Dharwad', slug: 'dharwad', state: 'Karnataka', tier: 'tier3', population: '316K+' },
  { name: 'Haldia', slug: 'haldia', state: 'West Bengal', tier: 'tier3', population: '200K+' },
  { name: 'Tinsukia', slug: 'tinsukia', state: 'Assam', tier: 'tier3', population: '125K+' },
  { name: 'Dibrugarh', slug: 'dibrugarh', state: 'Assam', tier: 'tier3', population: '138K+' },
  { name: 'Silchar', slug: 'silchar', state: 'Assam', tier: 'tier3', population: '228K+' },
  { name: 'Jorhat', slug: 'jorhat', state: 'Assam', tier: 'tier3', population: '68K+' },
  { name: 'Shillong', slug: 'shillong', state: 'Meghalaya', tier: 'tier3', population: '354K+' },
  { name: 'Aizawl', slug: 'aizawl', state: 'Mizoram', tier: 'tier3', population: '293K+' },
  { name: 'Kohima', slug: 'kohima', state: 'Nagaland', tier: 'tier3', population: '99K+' },
  { name: 'Gangtok', slug: 'gangtok', state: 'Sikkim', tier: 'tier3', population: '100K+' },
  { name: 'Itanagar', slug: 'itanagar', state: 'Arunachal Pradesh', tier: 'tier3', population: '44K+' },
  { name: 'Bhuj', slug: 'bhuj', state: 'Gujarat', tier: 'tier3', population: '150K+' },
  { name: 'Anand', slug: 'anand', state: 'Gujarat', tier: 'tier3', population: '197K+' },
  { name: 'Gandhinagar', slug: 'gandhinagar', state: 'Gujarat', tier: 'tier3', population: '292K+' },
  { name: 'Navsari', slug: 'navsari', state: 'Gujarat', tier: 'tier3', population: '168K+' },
  { name: 'Vapi', slug: 'vapi', state: 'Gujarat', tier: 'tier3', population: '153K+' },
  { name: 'Morbi', slug: 'morbi', state: 'Gujarat', tier: 'tier3', population: '194K+' },
  { name: 'Junagadh', slug: 'junagadh', state: 'Gujarat', tier: 'tier3', population: '320K+' },
  { name: 'Amreli', slug: 'amreli', state: 'Gujarat', tier: 'tier3', population: '78K+' },
  { name: 'Bhavnagar', slug: 'bhavnagar2', state: 'Gujarat', tier: 'tier2', population: '605K+' },
  { name: 'Palghar', slug: 'palghar', state: 'Maharashtra', tier: 'tier3', population: '105K+' },
  { name: 'Latur', slug: 'latur2', state: 'Maharashtra', tier: 'tier2', population: '382K+' },
  { name: 'Osmanabad', slug: 'osmanabad', state: 'Maharashtra', tier: 'tier3', population: '108K+' },
  { name: 'Sangli', slug: 'sangli', state: 'Maharashtra', tier: 'tier2', population: '436K+' },
  { name: 'Akola', slug: 'akola2', state: 'Maharashtra', tier: 'tier3', population: '425K+' },
  { name: 'Yavatmal', slug: 'yavatmal', state: 'Maharashtra', tier: 'tier3', population: '148K+' },
  { name: 'Nandurbar', slug: 'nandurbar', state: 'Maharashtra', tier: 'tier3', population: '92K+' }
];

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug);
}
